### ISSUE TITLE
Mandatory 2FA Across Eclipse Foundation GitHub Organizations

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/.github#6]
Just in case you missed the e-mail.
Starting April 30th, Eclipse will be enforcing mandatory Two-Factor Authentication (2FA) across all Eclipse Foundation owned GitHub organisations. 

see https://www.eclipse.org/lists/eclipse.org-committers/msg01409.html

Note: in the best case every committer activates 2FA (if not done yet) and we should be fine.

**Comment by relu91** [comment]
I've it already, so it should be fine.

**Comment by egekorkan** [comment]
I also have it and seems to work. @mkovatsc @sebastiankb @JKRhb @wiresio please activate it too :)

**Comment by JKRhb** [comment]
I also have activated already :)

**Comment by egekorkan** [comment]
All committers have it activated. Closing.
